# Generated by Django 3.0 on 2024-03-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='fin_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='FIN'),
        ),
    ]
