# Generated by Django 4.2.10 on 2024-03-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accident",
            old_name="time",
            new_name="accident_time",
        ),
    ]
