# Generated by Django 4.2.10 on 2024-03-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accident",
            old_name="date",
            new_name="accident_date",
        ),
        migrations.RenameField(
            model_name="vehicle",
            old_name="service_document",
            new_name="insurance_policy",
        ),
    ]
