# Generated by Django 4.2.10 on 2024-03-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agreementdocument",
            options={
                "verbose_name": "Insurance & Car Companies Agreement Document ",
                "verbose_name_plural": "Insurance & Car Companies Agreement Document ",
            },
        ),
        migrations.RemoveField(
            model_name="accidentbidding",
            name="company",
        ),
        migrations.AddField(
            model_name="accidentbidding",
            name="insurance_company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acc_comp",
                to="core.insurancecompany",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accidentbidding",
            name="insurance_company_agent",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acc_compag",
                to="core.insuranceagent",
            ),
            preserve_default=False,
        ),
    ]
