# Generated by Django 4.2.10 on 2024-03-02 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("A", "Insurance Agent"),
                    ("B", "Car Repair Company Agent"),
                    ("C", "Customer"),
                ],
                max_length=1,
            ),
        ),
    ]
