# Generated by Django 4.2.10 on 2024-03-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_time_accident_accident_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accident",
            name="accidentbidding_start_date",
            field=models.DateField(verbose_name="Accident bidding start date"),
        ),
    ]
