# Generated by Django 4.2.10 on 2024-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_agreementdocument_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="customer_fin",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Customer FIN"
            ),
        ),
    ]
