# Generated by Django 4.2.10 on 2024-03-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_myuser_registration_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="asset",
            options={"verbose_name": "Cihaz", "verbose_name_plural": "Cihaz"},
        ),
        migrations.AlterField(
            model_name="asset",
            name="service_document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="serv_doc",
                to="core.companydocument",
            ),
        ),
    ]
