# Generated by Django 3.0 on 2024-03-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_myuser_phone_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='insurance_policy',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accident_doc', to='core.InsurancePolicy'),
            preserve_default=False,
        ),
    ]
