# Generated by Django 4.2.10 on 2024-03-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_vehicle_customer_fin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("1", "Customer"),
                    ("2", "Car Repair Company Agent"),
                    ("3", "Insurance Agent"),
                ],
                max_length=1,
            ),
        ),
    ]
