# Generated by Django 4.2.10 on 2024-03-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_asset_options_alter_asset_service_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="service_document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="serv_doc",
                to="core.companydocument",
            ),
        ),
    ]
