# Generated by Django 4.2.10 on 2024-03-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_asset_service_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="plate_number",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="vin_code",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
