# Generated by Django 4.2.10 on 2024-03-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_myuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
