# Generated by Django 4.2.10 on 2024-03-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_asset_plate_number_alter_asset_vin_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="user_type",
            new_name="type",
        ),
        migrations.RemoveField(
            model_name="company",
            name="user",
        ),
    ]
