# Generated by Django 4.2.10 on 2024-03-05 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_myuser_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="fin_code",
            field=models.CharField(default=1, max_length=100, verbose_name="FIN"),
            preserve_default=False,
        ),
    ]
