# Generated by Django 4.2.10 on 2024-03-01 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_rename_user_type_company_type_remove_company_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="companydocument",
            name="customer_fin",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="companydocument",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comp_doc",
                to="core.customeruser",
            ),
        ),
    ]
