# Generated by Django 4.2.10 on 2024-03-01 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_companydocument_customer_fin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="customer_fin",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="myuser",
            name="fin_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cust_asset",
                to="core.customeruser",
            ),
        ),
    ]
