# Generated by Django 3.0.3 on 2024-03-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_agreementdocument_car_repair_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrepaircompanyoffer',
            name='accepted_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carrepaircompanyoffer',
            name='rejected_offer',
            field=models.BooleanField(default=False),
        ),
    ]
