# Generated by Django 3.0.3 on 2024-03-24 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240324_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrepaircompanyoffer',
            name='accident_bidding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AccidentBidding'),
        ),
    ]
