# Generated by Django 4.2.10 on 2024-03-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_asset_customer_fin_myuser_fin_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="company_user",
        ),
        migrations.RemoveField(
            model_name="case",
            name="document",
        ),
        migrations.AddField(
            model_name="case",
            name="asset",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_case",
                to="core.asset",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="case",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_cust",
                to="core.customeruser",
            ),
        ),
    ]
