# Generated by Django 4.2.10 on 2024-03-05 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_myuser_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={
                "permissions": (
                    ("can_see_staff_menu", "Can see Application menu on staff admin"),
                    ("can_view_warehouse_panel", "Can use Warehouse panel"),
                    ("can_change_user_permissions", "Can change user permissions"),
                    ("can_change_user_password", "Can change user password"),
                    ("can_change_own_password", "Can change own password"),
                    (
                        "can_change_staff_user_password",
                        "Can change staff user user password",
                    ),
                    ("can_change_user_email", "Can change user's email"),
                    ("can_change_user_name_surname", "Can change user's name/surname"),
                    (
                        "can_edit_user_position_fields",
                        "Can change user position fields",
                    ),
                ),
                "verbose_name": "User",
                "verbose_name_plural": "User",
            },
        ),
    ]
