# Generated by Django 4.2.10 on 2024-03-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0009_alter_myuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="myuser",
            options={"verbose_name": "User", "verbose_name_plural": "User"},
        ),
        migrations.AlterField(
            model_name="myuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="company_user_set",
                related_query_name="myuser",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="company_user_set",
                related_query_name="myuser",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
