# Generated by Django 4.2.10 on 2024-03-02 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_remove_case_company_user_remove_case_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="case",
            name="asset",
        ),
        migrations.AddField(
            model_name="case",
            name="service_document",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_doc",
                to="core.companydocument",
            ),
        ),
    ]
