# Generated by Django 4.2.10 on 2024-03-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_myuser_options_alter_myuser_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=255, unique=True, verbose_name="email address"
            ),
        ),
    ]
