# Generated by Django 3.0.3 on 2024-03-25 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240324_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accident',
            name='photos',
        ),
        migrations.CreateModel(
            name='AccidentPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='uploads/accident')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.Accident')),
            ],
        ),
        migrations.CreateModel(
            name='AccidentBiddingPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='uploads/bidding')),
                ('accident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.AccidentBidding')),
            ],
        ),
    ]
