# Generated by Django 4.2.10 on 2024-03-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_case_asset_case_service_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="company_b",
        ),
        migrations.AddField(
            model_name="competition",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comp_company",
                to="core.companyauser",
            ),
            preserve_default=False,
        ),
    ]
