# Generated by Django 4.2.10 on 2024-03-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_remove_competition_company_b_competition_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="winner",
        ),
    ]
