# Generated by Django 3.0.3 on 2024-03-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240325_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='accidentbidding',
            name='services_to_provide',
            field=models.ManyToManyField(to='core.OfferedServices'),
        ),
    ]
