# Generated by Django 4.2.10 on 2024-03-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_remove_competition_winner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comp_company",
                to="core.companya",
            ),
        ),
    ]
