# Generated by Django 3.0.3 on 2024-03-26 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_accidentbidding_services_to_provide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accident_cust', to='core.CustomerUser'),
        ),
        migrations.AlterField(
            model_name='accidentbidding',
            name='insurance_company_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acc_compag', to='core.InsuranceAgent'),
        ),
        migrations.AlterField(
            model_name='carrepaircompanyoffer',
            name='offer_owner_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CarRepairCompanyAgent'),
        ),
    ]
