# Generated by Django 4.2.10 on 2024-03-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_carrepaircompanyoffer_offer_owner_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="registration_date",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="Registration date"
            ),
        ),
    ]
