# Generated by Django 3.0.3 on 2024-03-26 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240326_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accidentbiddingphoto',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidd_photos', to='core.AccidentBidding'),
        ),
        migrations.AlterField(
            model_name='accidentphoto',
            name='accident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_photos', to='core.Accident'),
        ),
    ]
