# Generated by Django 3.0.3 on 2024-03-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240326_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone_prefix',
            field=models.CharField(choices=[('1', '050'), ('2', '051'), ('3', '077'), ('4', '070'), ('5', '055'), ('6', '010'), ('7', '099'), ('8', '060')], max_length=3),
        ),
    ]
