# Generated by Django 4.2.10 on 2024-03-02 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_agreementdocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("services_offered", models.CharField(max_length=255)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.competition",
                    ),
                ),
                (
                    "offer_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.companyb"
                    ),
                ),
            ],
        ),
    ]
