# Generated by Django 4.2.10 on 2024-03-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_companyoffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyoffer",
            name="reject",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="companyoffer",
            name="winner",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
