# Generated by Django 4.2.10 on 2024-03-11 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_myuser_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_user",
                to="core.company",
                verbose_name="company",
            ),
        ),
    ]
