# Generated by Django 3.0.3 on 2024-03-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20240326_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('1', 'in progress'), ('2', 'finished'), ('3', 'scheduled')], max_length=1),
        ),
    ]
