# Generated by Django 3.0.3 on 2024-03-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20240327_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
