# Generated by Django 3.0.3 on 2024-04-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20240406_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='contract_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
